name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
        with:
          sdk: 3.7.0

      - uses: kuhnroyal/flutter-fvm-config-action@c378498f1d1962d33039c3989411093ef8a17b2c # v3.3
        id: fvm-config-action

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}

      - name: install dependencies
        run: flutter pub get

      - name: Validate
        run: dart run devtools_extensions validate --package=.

      - name: Build and Copy
        run: dart run devtools_extensions build_and_copy --source=. --dest=./extension/devtools

      - name: Publish
        run: dart pub publish --force
